from django.urls import path

from . import api, views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("health/", views.health, name="health"),
    path("accounts/register/", views.register_customer_view, name="register"),
    path("dashboard/", views.dashboard_router, name="dashboard"),
    path("platform/", views.platform_dashboard, name="platform-dashboard"),
    path("platform/businesses/new/", views.platform_business_create, name="platform-business-create"),
    path("vendors/", views.vendor_directory, name="vendor-directory"),
    path("vendors/<slug:business_slug>/", views.vendor_detail, name="vendor-detail"),
    path("vendors/<slug:business_slug>/join/", views.join_vendor, name="join-vendor"),
    path("b/<slug:business_slug>/owner/", views.owner_dashboard, name="owner-dashboard"),
    path("b/<slug:business_slug>/staff/", views.staff_dashboard, name="staff-dashboard"),
    path("b/<slug:business_slug>/wallets/<uuid:wallet_id>/", views.owner_wallet_detail, name="owner-wallet-detail"),
    path("customer/", views.customer_dashboard, name="customer-dashboard"),
    path("customer/vendors/<slug:business_slug>/", views.customer_vendor_dashboard, name="customer-vendor-dashboard"),
    path("customer/payments/<uuid:payment_id>/", views.customer_payment_action, name="customer-payment-action"),
    path("customer/vendors/<slug:business_slug>/reviews/<int:location_id>/", views.mark_reviewed, name="mark-reviewed"),
    path("customer/notifications/<int:notification_id>/read/", views.mark_notification_read, name="notification-read"),
    path("customer/wallets/<uuid:wallet_id>/", views.customer_wallet_detail, name="customer-wallet-detail"),
    path("receipts/<str:bill_number>/", views.receipt, name="receipt"),
    path("sw.js", views.service_worker, name="service-worker"),
    path("api/v1/me/", api.MeView.as_view(), name="api-me"),
    path("api/v1/vendors/", api.VendorDirectoryView.as_view(), name="api-vendors"),
    path("api/v1/vendors/<slug:business_slug>/bootstrap/", api.VendorBootstrapView.as_view(), name="api-vendor-bootstrap"),
    path("api/v1/vendors/<slug:business_slug>/join/", api.VendorJoinView.as_view(), name="api-vendor-join"),
    path("api/v1/vendors/<slug:business_slug>/wallet/", api.VendorWalletView.as_view(), name="api-vendor-wallet"),
    path("api/v1/payments/<uuid:payment_id>/confirm/", api.CustomerPaymentConfirmView.as_view(), name="api-payment-confirm"),
    path("api/v1/notifications/", api.NotificationsView.as_view(), name="api-notifications"),
    path("api/v1/push-devices/", api.PushDeviceView.as_view(), name="api-push-devices"),
    path("api/v1/wallets/", api.MyWalletsView.as_view(), name="api-my-wallets"),
    path("api/v1/businesses/<slug:business_slug>/wallets/", api.BusinessWalletsView.as_view(), name="api-business-wallets"),
    path("api/v1/businesses/<slug:business_slug>/charge/", api.StaffChargeView.as_view(), name="api-charge"),
    path("api/v1/businesses/<slug:business_slug>/topup/", api.ManagerTopupView.as_view(), name="api-topup"),
    path("api/v1/businesses/<slug:business_slug>/refund/", api.ManagerRefundView.as_view(), name="api-refund"),
]
